calculation:
  type: dimer
  init_file: dimer_init.traj
  fmax: 0.05
  dimer_separation: 0.01
  max_num_rot: 3
  init_eigenmode_method: displacement # or gauss
  displacement_file: displacement_vector.npy

abacus:
  command: abacus
  mpi: 16
  omp: 1
  directory: run_dimer
  parameters:
    calculation: scf
    nspin: 2
    xc: pbe
    ecutwfc: 100
    ks_solver: genelpa
    smearing_method: gaussian
    smearing_sigma: 0.001
    basis_type: lcao
    mixing_type: broyden
    scf_thr: 1.0e-6
    scf_nmax: 100
    pp:
      C: C_ONCV_PBE-1.0.upf
    basis:
      C: C_gga_7au_100Ry_2s2p1d.orb
    pseudo_dir: "/path/to/PP"
    basis_dir: "/path/to/ORB"
    cal_force: 1
    cal_stress: 1
