calculation:
  type: d2s
  method: dimer # Options: dimer, sella
  init_file: init.stru
  final_file: final.stru

  # Rough NEB Phase
  neb:
    n_images: 8
    fmax: 0.8
    climb: true
    algorism: improvedtangent

  # Single-Ended Search Phase
  dimer: # Only used if method=dimer
    fmax: 0.05
    # separation: 0.01

  sella: # Only used if method=sella
    fmax: 0.05
    eta: 0.005

abacus:
  command: abacus
  mpi: 16
  omp: 1
  directory: run_d2s
  parameters:
    calculation: scf
    nspin: 2
    xc: pbe
    ecutwfc: 100
    # ... Add other DFT parameters here ...
    pp:
      C: C_ONCV_PBE-1.0.upf
    basis:
      C: C_gga_7au_100Ry_2s2p1d.orb
    pseudo_dir: "/path/to/PP"
    basis_dir: "/path/to/ORB"
    cal_force: 1
    cal_stress: 1
