calculation:
  type: vibration
  init_structure: ts_opt.stru
  delta: 0.01
  nfree: 2
  name: vib_calc
  temperature: 300.0

calculator:
  name: dp
  dp:
    model: /home/pku-jianghong/liuzhaoqing/work/deepmodeling/atst-tools/temp_repos/dp_model/DPA-3.1-3M.pt
