calculation:
  type: vibration
  init_structure: inputs/ts_opt.stru
  delta: 0.01
  nfree: 2
  name: vib_calc
  thermochemistry:
    temperature: 300.0

calculator:
  name: dp
  dp:
    model: ../../temp_repos/dp_model/DPA-3.1-3M.pt
    head: Omat24
    omp: 4
    share_calculator: true
