calculation:
  type: autoneb
  prefix: run_autoneb
  init_chain: inputs/init_neb_chain.traj
  n_simul: 4
  n_max: 10
  algorism: improvedtangent
  parallel: true
  optimizer: FIRE
  fmax: [0.20, 0.05]
  climb: true
  maxsteps: 100
  iter_folder: AutoNEB_iter

calculator:
  name: dp
  dp:
    model: ../../temp_repos/dp_model/DPA-3.1-3M.pt
    head: Domains_SSE_PBE
    omp: 4
    share_calculator: true
