calculation:
  type: irc
  init_structure: inputs/ts.stru
  trajectory: irc_reverse.traj
  direction: reverse
  fmax: 0.05
  max_steps: 1000
  dx: 0.1
  eta: 0.002

calculator:
  name: abacus
  abacus:
    command: abacus
    mpi: 4
    omp: 1
    directory: irc_reverse_run
    parameters:
      calculation: scf
      basis_type: lcao
      ks_solver: cusolver
      ecutwfc: 100
      scf_thr: 1e-6
      cal_force: 1
      pseudo_dir: ../data
      orbital_dir: ../data
      pseudopotentials:
        H: H_ONCV_PBE-1.0.upf
      basissets:
        H: H_gga_6au_100Ry_2s1p.orb
