calculation:
  type: sella
  init_file: sella_init.stru # Can be .stru or .traj
  fmax: 0.05
  eta: 0.005 # Sella parameter

abacus:
  command: abacus
  mpi: 16
  omp: 1
  directory: run_sella
  parameters:
    calculation: scf
    nspin: 2
    xc: pbe
    ecutwfc: 100
    ks_solver: genelpa
    smearing_method: gaussian
    smearing_sigma: 0.001
    basis_type: lcao
    mixing_type: broyden
    scf_thr: 1.0e-6
    scf_nmax: 100
    pp:
      C: C_ONCV_PBE-1.0.upf
    basis:
      C: C_gga_7au_100Ry_2s2p1d.orb
    pseudo_dir: "/path/to/PP"
    basis_dir: "/path/to/ORB"
    cal_force: 1
    cal_stress: 1
