calculation:
  type: neb
  make:
    init_structure: inputs/cy_pt_initial.traj
    final_structure: inputs/cy_pt_final.traj
    n_images: 5
    method: IDPP
    output: cy_pt_neb_5_images.traj
    no_align: true
  trajectory: neb_parallel_nested_mpi.traj
  climb: true
  fmax: 0.05
  k: 0.1
  algorism: improvedtangent
  parallel: true
  optimizer: FIRE
  max_steps: 10000
  endpoint_singlepoint: auto

calculator:
  name: abacus
  abacus:
    command: env -u OMPI_COMM_WORLD_SIZE -u OMPI_COMM_WORLD_RANK -u OMPI_COMM_WORLD_LOCAL_RANK -u OMPI_COMM_WORLD_LOCAL_SIZE -u OMPI_UNIVERSE_SIZE -u PMI_SIZE -u PMI_RANK -u PMIX_RANK -u PMIX_NAMESPACE -u MPI_LOCALRANKID mpirun -np {mpi} --host localhost:{mpi} --oversubscribe -map-by slot --bind-to none -mca ras ^slurm -mca plm isolated -mca rmaps_base_oversubscribe 1 -mca coll_hcoll_enable 0 abacus
    version_command: abacus --version
    mpi: 4
    omp: 8
    directory: neb_parallel_nested_mpi
    kpts: [2, 1, 2]
    parameters:
        calculation: scf
        nspin: 2
        dft_functional: pbe
        ecutwfc: 100
        basis_type: lcao
        ks_solver: cusolver
        vdw_method: d3_bj
        symmetry: 0
        scf_thr: 1e-06
        scf_nmax: 100
        smearing_method: gaussian
        smearing_sigma: 0.001
        mixing_type: broyden
        cal_force: 1
        cal_stress: 1
        init_wfc: atomic
        init_chg: atomic
        out_stru: 1
        out_chg: -1
        out_mul: 0
        out_bandgap: 0
        out_wfc_lcao: 0
        efield_flag: 1
        dip_cor_flag: 1
        efield_dir: 1
        pseudo_dir: ../data
        orbital_dir: ../data
        pseudopotentials:
           H: H_ONCV_PBE-1.0.upf
           C: C_ONCV_PBE-1.0.upf
           Pt: Pt_ONCV_PBE-1.0.upf
        basissets:
           H: H_gga_6au_100Ry_2s1p.orb
           C: C_gga_7au_100Ry_2s2p1d.orb
           Pt: Pt_gga_7au_100Ry_4s2p2d1f.orb
